-- ⚠️  LOCAL DEVELOPMENT ONLY — these values are NOT production secrets.
--   • SUPABASE_URL points at the local Docker stack (host.docker.internal:54321).
--   • The publishable/secret keys are the keys for the LOCAL Supabase instance
--     only. They grant no access to the cloud project — the cloud project uses
--     entirely different keys stored in .env.local (which is gitignored).
--   • Seeded into Vault by `supabase db reset` (see [db.seed] in config.toml) so
--     local edge functions can resolve secrets. Safe to commit.
--   • Regenerated by the AgentLink CLI; manual edits here may be overwritten on
--     the next scaffold / --force-update.

DO $$ DECLARE
  _id uuid;
BEGIN
  SELECT id INTO _id FROM vault.secrets WHERE name = 'SUPABASE_URL';
  IF _id IS NOT NULL THEN
    PERFORM vault.update_secret(_id, 'http://host.docker.internal:54321', 'SUPABASE_URL');
  ELSE
    PERFORM vault.create_secret('http://host.docker.internal:54321', 'SUPABASE_URL');
  END IF;
END $$;
DO $$ DECLARE
  _id uuid;
BEGIN
  SELECT id INTO _id FROM vault.secrets WHERE name = 'SUPABASE_PUBLISHABLE_KEY';
  IF _id IS NOT NULL THEN
    PERFORM vault.update_secret(_id, 'sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH', 'SUPABASE_PUBLISHABLE_KEY');
  ELSE
    PERFORM vault.create_secret('sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH', 'SUPABASE_PUBLISHABLE_KEY');
  END IF;
END $$;
DO $$ DECLARE
  _id uuid;
BEGIN
  SELECT id INTO _id FROM vault.secrets WHERE name = 'SUPABASE_SECRET_KEY';
  IF _id IS NOT NULL THEN
    PERFORM vault.update_secret(_id, 'sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz', 'SUPABASE_SECRET_KEY');
  ELSE
    PERFORM vault.create_secret('sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz', 'SUPABASE_SECRET_KEY');
  END IF;
END $$;
DO $$ DECLARE
  _id uuid;
BEGIN
  SELECT id INTO _id FROM vault.secrets WHERE name = 'ALLOWED_SIGNUP_DOMAINS';
  IF _id IS NOT NULL THEN
    PERFORM vault.update_secret(_id, '', 'ALLOWED_SIGNUP_DOMAINS');
  ELSE
    PERFORM vault.create_secret('', 'ALLOWED_SIGNUP_DOMAINS');
  END IF;
END $$;
