-- Initial agentlink bootstrap migration.
--
-- STATIC, hand-curated. NOT regenerated by pg-delta.
--
-- Sole purpose: install platform-level objects (extensions, schemas,
-- schema-level grants) so the larger generated migration that runs next
-- (20200101000001_initial_agentlink_scaffold.sql) can reference pgmq,
-- pg_net, pg_cron, and the `api` schema without ordering errors.
--
-- Why split this out:
--   pg-delta's `--integration supabase` plan emits CREATE EXTENSION at
--   the END of the plan rather than the start — after the api functions
--   that call pgmq.* in their bodies. LANGUAGE sql functions validate
--   identifiers at create time, so the plan errors out with
--   `schema "pgmq" does not exist` on `supabase db push`. By doing all
--   extension + schema setup in a separate, earlier-timestamped
--   migration, the generated migration can rely on every dependency
--   already existing in the DB.
--
-- Mirrors the declarative source of truth:
--   - cli/src/template/supabase/schemas/_extensions.sql
--   - cli/src/template/supabase/schemas/_schemas.sql
-- Drift between this file and those is a bug. Keep them in sync when
-- adding/removing platform plumbing.
--
-- Idempotent on purpose. Once `supabase db push` records this migration
-- it won't re-run it, but the IF [NOT] EXISTS / CASCADE forms keep
-- partial-state recovery (and re-applies on dev) safe.

-- ─────────────────────────────────────────────────────────────────────
-- Extensions
-- ─────────────────────────────────────────────────────────────────────

-- AgentLink enforces strict schema isolation: only the `api` schema is
-- exposed via PostgREST, and all access flows through RPC functions.
-- Leaving pg_graphql enabled would bypass that boundary by exposing the
-- DB at /graphql/v1. CASCADE because Supabase pre-installs pg_graphql
-- and may have created auxiliary objects against it.
DROP EXTENSION IF EXISTS pg_graphql CASCADE;

-- Async HTTP from SQL (fire-and-forget edge-function invocations from
-- _internal_admin_call_edge_function, queue dispatch, cron).
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- In-DB scheduler. Cloud installs cron objects in pg_catalog by
-- convention; matching that placement keeps `info` output consistent
-- across environments.
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;

-- Transactional message queue. Auto-creates its own `pgmq` schema, which
-- the api._admin_queue_* functions reference directly.
CREATE EXTENSION IF NOT EXISTS pgmq VERSION '1.5.1';

-- ─────────────────────────────────────────────────────────────────────
-- Schemas
-- ─────────────────────────────────────────────────────────────────────

-- The only schema exposed via PostgREST / Supabase Data API. Tables and
-- internal helpers live in `public`; client-callable RPCs live here as
-- api.{entity}_{action}. Granting USAGE to anon makes anonymous calls
-- to explicitly-anon-granted RPCs (e.g. signup-adjacent helpers) work;
-- per-function EXECUTE is still the security boundary.
CREATE SCHEMA IF NOT EXISTS api;

GRANT USAGE ON SCHEMA api TO anon, authenticated, service_role;

-- EXECUTE on existing functions: no-op at bootstrap time (no functions
-- yet), but keeps the grant explicit so the schema's posture is
-- self-documenting after a partial re-apply.
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA api TO authenticated, service_role;

-- Default privileges so every future RPC created in api/ inherits
-- EXECUTE for authenticated + service_role without needing per-function
-- grants. Matches what the generated migration would otherwise emit, but
-- earlier, so the function bodies in the next migration parse cleanly.
ALTER DEFAULT PRIVILEGES IN SCHEMA api
  GRANT EXECUTE ON FUNCTIONS TO authenticated, service_role;
